BEGIN TRANSACTION;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS offense_stats;
DROP TABLE IF EXISTS offense_proj;
DROP TABLE IF EXISTS defense_stats;
DROP TABLE IF EXISTS defense_proj;
DROP TABLE IF EXISTS teams;

CREATE TABLE users (
	user_id SERIAL,
	username varchar(50) NOT NULL UNIQUE,
	password_hash varchar(200) NOT NULL,
	role varchar(50) NOT NULL,
	CONSTRAINT PK_user PRIMARY KEY (user_id)
);

CREATE TABLE offense_stats (
    GameKey VARCHAR(10),
    PlayerID INT,
    SeasonType INT,
    Season INT,
    GameDate TIMESTAMP,
    Week INT,
    Team VARCHAR(3),
    Opponent VARCHAR(3),
    HomeOrAway VARCHAR(5),
    Number INT,
    Name VARCHAR(255),
    Position VARCHAR(5),
    PositionCategory VARCHAR(5),
    Played INT,
    Started INT,
    PassingAttempts DECIMAL(8, 2),
    PassingCompletions DECIMAL(8, 2),
    PassingYards DECIMAL(8, 2),
    PassingCompletionPercentage DECIMAL(5, 2),
    PassingYardsPerAttempt DECIMAL(5, 2),
    PassingYardsPerCompletion DECIMAL(5, 2),
    PassingTouchdowns DECIMAL(5, 2),
    PassingInterceptions DECIMAL(5, 2),
    PassingRating DECIMAL(5, 2),
    PassingLong DECIMAL(8, 2),
    PassingSacks DECIMAL(5, 2),
    PassingSackYards DECIMAL(5, 2),
    RushingAttempts DECIMAL(8, 2),
    RushingYards DECIMAL(8, 2),
    RushingYardsPerAttempt DECIMAL(5, 2),
    RushingTouchdowns DECIMAL(5, 2),
    RushingLong DECIMAL(8, 2),
    ReceivingTargets DECIMAL(8, 2),
    Receptions DECIMAL(8, 2),
    ReceivingYards DECIMAL(8, 2),
    ReceivingYardsPerReception DECIMAL(5, 2),
    ReceivingTouchdowns DECIMAL(5, 2),
    ReceivingLong DECIMAL(8, 2),
    Fumbles DECIMAL(5, 2),
    FumblesLost DECIMAL(5, 2),
    PuntReturns DECIMAL(5, 2),
    PuntReturnYards DECIMAL(8, 2),
    PuntReturnTouchdowns DECIMAL(5, 2),
    KickReturns DECIMAL(5, 2),
    KickReturnYards DECIMAL(8, 2),
    KickReturnTouchdowns DECIMAL(5, 2),
    SoloTackles DECIMAL(5, 2),
    AssistedTackles DECIMAL(5, 2),
    TacklesForLoss DECIMAL(5, 2),
    Sacks DECIMAL(5, 2),
    SackYards DECIMAL(5, 2),
    QuarterbackHits DECIMAL(5, 2),
    PassesDefended DECIMAL(5, 2),
    FumblesForced DECIMAL(5, 2),
    FumblesRecovered DECIMAL(5, 2),
    FumbleReturnTouchdowns DECIMAL(5, 2),
    Interceptions DECIMAL(5, 2),
    InterceptionReturnTouchdowns DECIMAL(5, 2),
    FieldGoalsAttempted DECIMAL(5, 2),
    FieldGoalsMade DECIMAL(5, 2),
    ExtraPointsMade DECIMAL(5, 2),
    TwoPointConversionPasses DECIMAL(5, 2),
    TwoPointConversionRuns DECIMAL(5, 2),
    TwoPointConversionReceptions DECIMAL(5, 2),
    FantasyPoints DECIMAL(5, 2),
    FantasyPointsPPR DECIMAL(5, 2),
    FantasyPosition VARCHAR(5),
    PlayerGameID INT,
    ExtraPointsAttempted DECIMAL(5, 2),
    FantasyPointsFanDuel DECIMAL(5, 2),
    FieldGoalsMade0to19 DECIMAL(5, 2),
    FieldGoalsMade20to29 DECIMAL(5, 2),
    FieldGoalsMade30to39 DECIMAL(5, 2),
    FieldGoalsMade40to49 DECIMAL(5, 2),
    FieldGoalsMade50Plus DECIMAL(5, 2),
    FantasyPointsDraftKings DECIMAL(5, 2),
    InjuryStatus VARCHAR(255),
    TeamID INT,
    OpponentID INT,
    ScoreID INT,
    SnapCountsConfirmed BOOLEAN
);


CREATE TABLE offense_proj (
    GameKey VARCHAR(10),
    PlayerID INT,
    SeasonType INT,
    Season INT,
    GameDate TIMESTAMP,
    Week INT,
    Team VARCHAR(3),
    Opponent VARCHAR(3),
    HomeOrAway VARCHAR(5),
    Number INT,
    Name VARCHAR(255),
    Position VARCHAR(5),
    PositionCategory VARCHAR(5),
    Played INT,
    Started INT,
    PassingAttempts DECIMAL(8, 2),
    PassingCompletions DECIMAL(8, 2),
    PassingYards DECIMAL(8, 2),
    PassingCompletionPercentage DECIMAL(5, 2),
    PassingYardsPerAttempt DECIMAL(5, 2),
    PassingYardsPerCompletion DECIMAL(5, 2),
    PassingTouchdowns DECIMAL(5, 2),
    PassingInterceptions DECIMAL(5, 2),
    PassingRating DECIMAL(5, 2),
    PassingLong DECIMAL(8, 2),
    PassingSacks DECIMAL(5, 2),
    PassingSackYards DECIMAL(5, 2),
    RushingAttempts DECIMAL(8, 2),
    RushingYards DECIMAL(8, 2),
    RushingYardsPerAttempt DECIMAL(5, 2),
    RushingTouchdowns DECIMAL(5, 2),
    RushingLong DECIMAL(8, 2),
    ReceivingTargets DECIMAL(8, 2),
    Receptions DECIMAL(8, 2),
    ReceivingYards DECIMAL(8, 2),
    ReceivingYardsPerReception DECIMAL(5, 2),
    ReceivingTouchdowns DECIMAL(5, 2),
    ReceivingLong DECIMAL(8, 2),
    Fumbles DECIMAL(5, 2),
    FumblesLost DECIMAL(5, 2),
    PuntReturns DECIMAL(5, 2),
    PuntReturnYards DECIMAL(8, 2),
    PuntReturnTouchdowns DECIMAL(5, 2),
    KickReturns DECIMAL(5, 2),
    KickReturnYards DECIMAL(8, 2),
    KickReturnTouchdowns DECIMAL(5, 2),
    SoloTackles DECIMAL(5, 2),
    AssistedTackles DECIMAL(5, 2),
    TacklesForLoss DECIMAL(5, 2),
    Sacks DECIMAL(5, 2),
    SackYards DECIMAL(5, 2),
    QuarterbackHits DECIMAL(5, 2),
    PassesDefended DECIMAL(5, 2),
    FumblesForced DECIMAL(5, 2),
    FumblesRecovered DECIMAL(5, 2),
    FumbleReturnTouchdowns DECIMAL(5, 2),
    Interceptions DECIMAL(5, 2),
    InterceptionReturnTouchdowns DECIMAL(5, 2),
    FieldGoalsAttempted DECIMAL(5, 2),
    FieldGoalsMade DECIMAL(5, 2),
    ExtraPointsMade DECIMAL(5, 2),
    TwoPointConversionPasses DECIMAL(5, 2),
    TwoPointConversionRuns DECIMAL(5, 2),
    TwoPointConversionReceptions DECIMAL(5, 2),
    FantasyPoints DECIMAL(5, 2),
    FantasyPointsPPR DECIMAL(5, 2),
    FantasyPosition VARCHAR(5),
    PlayerGameID INT,
    ExtraPointsAttempted DECIMAL(5, 2),
    FantasyPointsFanDuel DECIMAL(5, 2),
    FieldGoalsMade0to19 DECIMAL(5, 2),
    FieldGoalsMade20to29 DECIMAL(5, 2),
    FieldGoalsMade30to39 DECIMAL(5, 2),
    FieldGoalsMade40to49 DECIMAL(5, 2),
    FieldGoalsMade50Plus DECIMAL(5, 2),
    FantasyPointsDraftKings DECIMAL(5, 2),
    InjuryStatus VARCHAR(255),
    TeamID INT,
    OpponentID INT,
    ScoreID INT,
    SnapCountsConfirmed BOOLEAN
);

CREATE TABLE defense_stats (
    GameKey VARCHAR(10),
    SeasonType INT,
    Season INT,
    Week INT,
    Date TIMESTAMP,
    Team VARCHAR(3),
    Opponent VARCHAR(3),
    PointsAllowed DECIMAL(5, 2),
    TouchdownsScored DECIMAL(5, 2),
    Sacks DECIMAL(5, 2),
    SackYards DECIMAL(5, 2),
    FumblesForced DECIMAL(5, 2),
    FumblesRecovered DECIMAL(5, 2),
    FumbleReturnTouchdowns DECIMAL(5, 2),
    Interceptions DECIMAL(5, 2),
    InterceptionReturnTouchdowns DECIMAL(5, 2),
    BlockedKicks DECIMAL(5, 2),
    Safeties DECIMAL(5, 2),
    PuntReturnTouchdowns DECIMAL(5, 2),
    KickReturnTouchdowns DECIMAL(5, 2),
    BlockedKickReturnTouchdowns DECIMAL(5, 2),
    FieldGoalReturnTouchdowns DECIMAL(5, 2),
    QuarterbackHits DECIMAL(5, 2),
    TacklesForLoss DECIMAL(5, 2),
    DefensiveTouchdowns DECIMAL(5, 2),
    SpecialTeamsTouchdowns INT,
    FantasyPoints DECIMAL(5, 2),
    PointsAllowedByDefenseSpecialTeams DECIMAL(5, 2),
    TwoPointConversionReturns DECIMAL(5, 2),
    FantasyPointsFanDuel DECIMAL(5, 2),
    FantasyPointsDraftKings DECIMAL(5, 2),
    PlayerID INT,
    HomeOrAway VARCHAR(5),
    TeamID INT,
    OpponentID INT,
    ScoreID INT
);

CREATE TABLE defense_proj (
    GameKey VARCHAR(10),
    SeasonType INT,
    Season INT,
    Week INT,
    Date TIMESTAMP,
    Team VARCHAR(3),
    Opponent VARCHAR(3),
    PointsAllowed DECIMAL(5, 2),
    TouchdownsScored DECIMAL(5, 2),
    Sacks DECIMAL(5, 2),
    SackYards DECIMAL(5, 2),
    FumblesForced DECIMAL(5, 2),
    FumblesRecovered DECIMAL(5, 2),
    FumbleReturnTouchdowns DECIMAL(5, 2),
    Interceptions DECIMAL(5, 2),
    InterceptionReturnTouchdowns DECIMAL(5, 2),
    BlockedKicks DECIMAL(5, 2),
    Safeties DECIMAL(5, 2),
    PuntReturnTouchdowns DECIMAL(5, 2),
    KickReturnTouchdowns DECIMAL(5, 2),
    BlockedKickReturnTouchdowns DECIMAL(5, 2),
    FieldGoalReturnTouchdowns DECIMAL(5, 2),
    QuarterbackHits DECIMAL(5, 2),
    TacklesForLoss DECIMAL(5, 2),
    DefensiveTouchdowns DECIMAL(5, 2),
    SpecialTeamsTouchdowns INT,
    FantasyPoints DECIMAL(5, 2),
    PointsAllowedByDefenseSpecialTeams DECIMAL(5, 2),
    TwoPointConversionReturns DECIMAL(5, 2),
    FantasyPointsFanDuel DECIMAL(5, 2),
    FantasyPointsDraftKings DECIMAL(5, 2),
    PlayerID INT,
    HomeOrAway VARCHAR(5),
    TeamID INT,
    OpponentID INT,
    ScoreID INT
);

CREATE TABLE teams (
    Key VARCHAR(3),
    TeamID INT PRIMARY KEY,
    PlayerID INT,
    City VARCHAR(255),
    Name VARCHAR(255),
    Conference VARCHAR(255),
    Division VARCHAR(255),
    FullName VARCHAR(255),
    StadiumID INT,
    ByeWeek INT,
    AverageDraftPosition DECIMAL(8, 2),
    AverageDraftPositionPPR DECIMAL(8, 2),
    PrimaryColor VARCHAR(6),
    SecondaryColor VARCHAR(6),
    TertiaryColor VARCHAR(6),
    QuaternaryColor VARCHAR(6),
    WikipediaLogoUrl VARCHAR(255),
    WikipediaWordMarkUrl VARCHAR(255),
    DraftKingsName VARCHAR(255),
    DraftKingsPlayerID INT,
    FanDuelName VARCHAR(255),
    FanDuelPlayerID INT,
    AverageDraftPosition2QB DECIMAL(8, 2),
    AverageDraftPositionDynasty DECIMAL(8, 2)
);


ALTER TABLE offense_stats
ADD FOREIGN KEY (TeamID) REFERENCES teams(TeamID);

ALTER TABLE offense_proj
ADD FOREIGN KEY (TeamID) REFERENCES teams(TeamID);

ALTER TABLE defense_stats
ADD FOREIGN KEY (TeamID) REFERENCES teams(TeamID);

ALTER TABLE defense_proj
ADD FOREIGN KEY (TeamID) REFERENCES teams(TeamID);


COMMIT TRANSACTION;
