export const configValueOptions = {
    'currentWeek': { 
        1: 'Week 1', 
        2: 'Week 2',
        3: 'Week 3',
        4: 'Week 4',
        5: 'Week 5',
        6: 'Week 6',
        7: 'Week 7',
        8: 'Week 8',
        9: 'Week 9',
        10: 'Week 10',
        11: 'Week 11',
        12: 'Week 12',
        13: 'Week 13',
        14: 'Week 14',
        15: 'Week 15',
        16: 'Week 16',
        17: 'Week 17',
        18: 'Week 18',
        19: 'Wild Card',
        20: 'Divisional',
        21: 'Conf Championship',
        22: 'Super Bowl' 
    },
    'currentLineupWeek': [1, 2, 3, 4],
    'lockRosters': { 1: 'True', 2: 'False' },
    'lockLineups': { 1: 'True', 2: 'False' },
    'startingLineupWeek': { 
        1: 'Week 1', 
        2: 'Week 2', 
        3: 'Week 3', 
        4: 'Week 4', 
        5: 'Week 5',
        6: 'Week 6',
        7: 'Week 7',
        8: 'Week 8',
        9: 'Week 9',
        10: 'Week 10',
        11: 'Week 11',
        12: 'Week 12',
        13: 'Week 13',
        14: 'Week 14',
        15: 'Week 15',
        16: 'Week 16',
        17: 'Week 17',
        18: 'Week 18',
        19: 'Wild Card'
    },
    'lineupWeek1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    'lineupWeek2': [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'lineupWeek3': [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
    'lineupWeek4': [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
};
export const configKeyDisplayNames = {
    'currentWeek': 'Current Week',
    'currentLineupWeek': 'Current Lineup Week',
    'lockRosters': 'Lock Rosters',
    'lockLineups': 'Lock Lineups',
    'startingLineupWeek': 'Starting Lineup Week',
    'lineupWeek1': 'Lineup Week One',
    'lineupWeek2': 'Lineup Week Two',
    'lineupWeek3': 'Lineup Week Three',
    'lineupWeek4': 'Lineup Week Four',
};
export const teamNameDisplayNames = {
    'ARI': 'Arizona Cardinals',
    'ATL': 'Atlanta Falcons',
    'BAL': 'Baltimore Ravens',
    'BUF': 'Buffalo Bills',
    'CAR': 'Carolina Panthers',
    'CHI': 'Chicago Bears',
    'CIN': 'Cincinnati Bengals',
    'CLE': 'Cleveland Browns',
    'DAL': 'Dallas Cowboys',
    'DEN': 'Denver Broncos',
    'DET': 'Detroit Lions',
    'GB': 'Green Bay Packers',
    'HOU': 'Houston Texans',
    'IND': 'Indianapolis Colts',
    'JAX': 'Jacksonville Jaguars',
    'KC': 'Kansas City Chiefs',
    'LAC': 'Los Angeles Chargers',
    'LAR': 'Los Angeles Rams',
    'LV': 'Las Vegas Raiders',
    'MIA': 'Miami Dolphins',
    'MIN': 'Minnesota Vikings',
    'NE': 'New England Patriots',
    'NO': 'New Orleans Saints',
    'NYG': 'New York Giants',
    'NYJ': 'New York Jets',
    'PHI': 'Philadelphia Eagles',
    'PIT': 'Pittsburgh Steelers',
    'SEA': 'Seattle Seahawks',
    'SF': 'San Francisco 49ers',
    'TB': 'Tampa Bay Buccaneers',
    'TEN': 'Tennessee Titans',
    'WAS': 'Washington Football Team'
};